#!/usr/bin/env python3
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
"""Trace Ascend C codegen artifacts that survive after a failed build."""

import argparse
import glob
import logging
import os
import sys
from pathlib import Path

from common import DTYPE_TO_MACRO, DTYPE_TO_ORIG, find_build_dir, find_work_dirs, load_json

LOG = logging.getLogger(__name__)

# codegen 产出的 .py 里值得打印的行；与算子名无关，任何算子都适用。
PY_KEYWORDS = (
    'def ', 'options', 'DTYPE', 'ORIG_DTYPE', 'FORMAT_',
    'compile_op', 'src_file', 'get_kernel_source',
    'kernel_name', 'ascendc_src', 'origin_func_name',
    'soc_version', 'impl_mode', 'HIGH_PERFORMANCE',
    '-x', 'cce', 'def _build_args',
)


def _print_python_file(py_path):
    LOG.info("\n  📄 %s", py_path)
    LOG.info("     (This Python file was generated by ascendc_impl_build.py)")
    LOG.info("     (It is what actually calls compile_op() with your kernel source)")
    with open(py_path, encoding="utf-8", errors="replace") as handle:
        lines = handle.read().split('\n')
    for line_number, line in enumerate(lines, 1):
        stripped = line.strip()
        if not any(keyword in stripped for keyword in PY_KEYWORDS):
            continue
        LOG.info("  %4d │ %s", line_number, line.rstrip())
        if 'compile_op(' not in stripped:
            continue
        for follow in range(line_number, min(line_number + 5, len(lines))):
            LOG.info("  %4d │ %s", follow + 1, lines[follow].rstrip())
        break


def show_codegen_python(work_dir):
    LOG.info("\n" + "─" * 70)
    LOG.info("1. CODEGEN'D PYTHON IMPLEMENTATION (the actual compilation driver)")
    LOG.info("─" * 70)
    py_files = sorted(glob.glob(os.path.join(work_dir, "dynamic", "*.py")))
    if not py_files:
        LOG.info("  ❌ No codegen'd .py found")
        return
    for py_path in py_files:
        _print_python_file(py_path)


def _print_param_file(param_path, node):
    inputs = node.get("inputs", [])
    outputs = node.get("outputs", [])
    attrs = node.get("attrs", [])
    dtype = inputs[0].get("dtype", "?") if inputs else "?"
    fmt = inputs[0].get("format", "?") if inputs else "?"
    macro = DTYPE_TO_MACRO.get(dtype, "?")
    orig = DTYPE_TO_ORIG.get(dtype, "?")
    LOG.info("\n  📄 %s", Path(param_path).name)
    LOG.info("    bin_filename: %s", node.get("bin_filename", "?"))
    LOG.info("    dtype: %s  format: %s", dtype, fmt)
    LOG.info("    ─────────────────────────────────")
    LOG.info("    This variant will compile with:")
    LOG.info("      -DDTYPE_X=%s", macro)
    LOG.info("      -DORIG_DTYPE_X=%s", orig)
    LOG.info("      -DFORMAT_X=FORMAT_%s", fmt)
    LOG.info("    ─────────────────────────────────")
    LOG.info("    inputs:")
    for item in inputs:
        LOG.info("      %-12s dtype=%-10s format=%-6s paramType=%s", item.get("name", "?"),
                 item.get("dtype", "?"), item.get("format", "?"), item.get("paramType", "?"))
    LOG.info("    outputs:")
    for item in outputs:
        LOG.info("      %-12s dtype=%-10s format=%-6s paramType=%s", item.get("name", "?"),
                 item.get("dtype", "?"), item.get("format", "?"), item.get("paramType", "?"))
    LOG.info("    attrs:")
    for attr in attrs:
        LOG.info("      %-20s dtype=%-6s value=%s", attr.get("name", "?"), attr.get("dtype", "?"),
                 attr.get("value", "?"))


def show_param_jsons(work_dir):
    LOG.info("\n" + "─" * 70)
    LOG.info("2. _param.json FILES (dtype-specific compile parameters)")
    LOG.info("─" * 70)
    param_files = sorted(glob.glob(os.path.join(work_dir, "bin_param", "*_param.json")))
    param_files += sorted(glob.glob(os.path.join(work_dir, "*_param.json")))
    if not param_files:
        LOG.info("  (No _param.json found)")
        return
    for param_path in param_files:
        data = load_json(param_path)
        if not data:
            LOG.info("\n  ⚠️  %s 无法解析（构建被中断时可能写了一半）", Path(param_path).name)
            continue
        for node in data.get("op_list", []):
            _print_param_file(param_path, node)


def _print_compile_script(script_path):
    LOG.info("\n  📄 %s", Path(script_path).name)
    with open(script_path, encoding="utf-8", errors="replace") as handle:
        lines = handle.read().split('\n')
    for line in lines:
        if 'asc_opc' in line:
            LOG.info("    CMD: %s", line.strip())
            break
    for line in lines:
        if 'tiling_key' in line:
            LOG.info("    TILING: %s", line.strip())
        if 'kernel-template-input' in line:
            LOG.info("    TPL: %s", line.strip())
    LOG.info("    (Full script: %s)", script_path)


def show_compile_scripts(work_dir):
    LOG.info("\n" + "─" * 70)
    LOG.info("3. .sh COMPILE SCRIPTS (actual asc_opc commands)")
    LOG.info("─" * 70)
    script_files = sorted(glob.glob(os.path.join(work_dir, "bin_param", "*.sh")))
    script_files += sorted(glob.glob(os.path.join(work_dir, "*.sh")))
    if not script_files:
        LOG.info("  (No .sh compile scripts found)")
        return
    for script_path in script_files:
        _print_compile_script(script_path)


def show_kernel_source(build_dir):
    LOG.info("\n" + "─" * 70)
    LOG.info("4. KERNEL SOURCE (as seen by the compiler)")
    LOG.info("─" * 70)
    pattern = str(build_dir / "**" / "binary" / "dynamic" / "**" / "*.cpp")
    sources = [path for path in glob.glob(pattern, recursive=True) if "_CPack_Packages" not in path]
    if sources:
        for source in sorted(sources):
            LOG.info("\n  📄 %s", source)
            LOG.info("     (This is the copy of your kernel source that was actually compiled)")
        return
    LOG.info("  (No kernel source copy found in build dir)")
    LOG.info("  → asc_opc reads the original op_kernel/<op>_apt.cpp")
    LOG.info("    via the path recorded in the codegen'd <OpType>.py")


def show_error_mapping_hint(work_dir):
    LOG.info("\n" + "─" * 70)
    LOG.info("5. ERROR MAPPING GUIDE")
    LOG.info("─" * 70)
    py_files = sorted(glob.glob(os.path.join(work_dir, "dynamic", "*.py")))
    if not py_files:
        return
    driver = py_files[0]
    LOG.info("""
  When asc_opc reports an error, the source file it references is
  NOT your original .cpp. The compilation chain is:

    Your .cpp  →  %s (codegen)  →  asc_opc compiles

  To map an error back to your source:

  1. Check the error's file path:
     - If it says "*.py" → the error is in codegen, check %s
     - If it says "<op>_apt.cpp" → it IS your source, but the
       line numbers may be shifted by macro expansion

  2. Check which dtype variant failed:
     - Look at the .sh script that failed (in bin_param/)
     - The --input_param=*.json tells you which dtype was being compiled
     - The -DDTYPE_X=<macro> tells you what your DTYPE_X expanded to

  3. Check TPL template instantiation:
     - If error mentions RANK or template specialization:
       → Check ASCENDC_TPL_ARGS_DECL and ASCENDC_TPL_SEL in _struct.h
       → Each ASCENDC_TPL_ARGS_SEL line = one expected sub-kernel
       → Missing SEL = missing instantiation = compile error

  4. Check the actual compile command:
     - Read the .sh file to see EXACTLY what flags were passed
     - Compare with what you expect
""", Path(driver).name, driver)


def main():
    parser = argparse.ArgumentParser(description="Trace Ascend C codegen artifacts")
    parser.add_argument("build_dir", help="Build directory (required)")
    parser.add_argument("--op-type", default=None, help="Filter by op type")
    args = parser.parse_args()
    build_dir = find_build_dir(args.build_dir)
    if not build_dir:
        LOG.error("ERROR: build directory not found: %s", args.build_dir)
        return 2
    logging.basicConfig(stream=sys.stdout, level=logging.INFO, format="%(message)s")
    build_dir = Path(build_dir)
    LOG.info("═" * 70)
    LOG.info("  Ascend C Codegen Source Tracer")
    LOG.info("═" * 70)
    LOG.info("  Build directory: %s", build_dir)
    work_dirs = find_work_dirs(build_dir, args.op_type)
    if not work_dirs:
        LOG.info("\n  ❌ No codegen working directories found.")
        LOG.info("     This means either:")
        LOG.info("     a) The build succeeded without --save-temp-files → use inspect_build.py instead")
        LOG.info("     b) The build failed before codegen ran → check CMake/op_build errors")
        return 1
    for work_dir in work_dirs:
        LOG.info("\n  📁 Codegen working dir: %s", work_dir)
        show_codegen_python(work_dir)
        show_param_jsons(work_dir)
        show_compile_scripts(work_dir)
        show_error_mapping_hint(work_dir)
    show_kernel_source(build_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
